### ISSUE TITLE
[payments] Consume meta config data

### ISSUE THREAD

**Issue by ianb** [mozilla/fxa#1280]
This is a followup to #1160 and #1275:

That PR adds a `<meta>` tag to the page, that is in the format that can be consume by [config-loader.js](https://github.com/mozilla/fxa/blob/master/packages/fxa-content-server/app/scripts/lib/config-loader.js)

We should:

- [ ] Move config-loader.js into some shared location usable by both servers
- [ ] Maybe remove underscore from that library (since it's used for something trivial)
- [ ] Include it in the payments server
- [ ] Use the config data in the payments server
- [ ] Maybe rename `fxa-content-server/config` to a more neutral `fxa-config`
