### ISSUE TITLE
Close out FxA-49 milestone "CDN"

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa#132]
Once we've got the CDN deployed in production, let's gather the metrics and summarize the impact of the feature back into the feature card for future reference.

**Comment by shane-tomlinson** [comment]
* https://github.com/mozilla/fxa-dev/issues/235
* https://github.com/mozilla-services/puppet-config/pull/1766

**Comment by shane-tomlinson** [comment]
cc @jrgm

**Comment by vladikoff** [comment]
waiting for fxa-dev to get a cdn going with lcip CNAME and certs

**Comment by vladikoff** [comment]
Blocked on https://github.com/mozilla/fxa-dev/pull/237  + deploy stage / prod

**Comment by rfk** [comment]
Is the deployment of this work tracked somewhere, e.g. a bugzilla deploy bug?

**Comment by vladikoff** [comment]
@jbuck says this is also blocked by ELB configuration. @jrgm to confirm.

@jbuck can you clarify?

**Comment by jbuck** [comment]
For each deploy we create a new ELB. CDN configuration changes take about 15 minutes to process, so we'd be looking at a 30 minute rollback period. We could add another Route53 entry and have the CDN always point at that and on promotion change that to point at the correct ELB... but I'd prefer have a single persistent ELB and not have to change CDN or DNS config at all.

**Comment by jbuck** [comment]
I do have the persistent ELB patch up for review right now, so I don't think this should be a significant blocker for the CDN deployment.

**Comment by shane-tomlinson** [comment]
High level tracking bug on bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1277532

Component bugs:
* [ ] https://bugzilla.mozilla.org/show_bug.cgi?id=1277538 (Review and merge fxa-dev changes)
* [ ] https://bugzilla.mozilla.org/show_bug.cgi?id=1277539 (Set up persistent ELB)
* [ ] https://bugzilla.mozilla.org/show_bug.cgi?id=1277541 (Deploy latest.dev.lcip.org static resources to CDN)
* [ ] https://bugzilla.mozilla.org/show_bug.cgi?id=1277542 (Deploy accounts.stage.mozaws.net static resources to CDN)
* [ ] https://bugzilla.mozilla.org/show_bug.cgi?id=1277543 (Deploy accounts.firefox.com static resources to CDN)

**Comment by vladikoff** [comment]
might close this and use fxa-features to track this instead.

**Comment by vladikoff** [comment]
CDN moved to train 66

**Comment by vladikoff** [comment]
It is now in FXA-Features under Shipping: https://github.com/mozilla/fxa-features/issues/7
