### ISSUE TITLE
Close out FxA-57 "Reminders" milestone

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa#138]
#### PR Order:
 
- [x] DB: https://github.com/mozilla/fxa-auth-db-mysql/pull/127
- [x] Mailer: https://github.com/mozilla/fxa-auth-mailer/pull/123
- [x] Auth Server: https://github.com/mozilla/fxa-auth-server/pull/1203 (with feature disabled in prod)

- [x] fxa-dev PR: https://github.com/mozilla/fxa-dev/pull/239
- [x] add statsd events, activity events PR, we can add this while we deploy the latest code with the feature turned off)

### Testing
 
> Here's a quick guide to help test the feature, it might be easire to clone another `fxa-local-dev` for this so you don't have to relink the different branches for other features.

Locally you need to `npm link` a few things:
 - link fxa-auth-db-mysql in `fxa-auth-mailer`.
 - link db-mysql and mailer in `fxa-auth-server`.

 (might throw `.bin` issues, just delete the bin) 

Run https://www.npmjs.com/package/maildev with `sudo maildev -s 9999 `:

<img src=https://cloud.githubusercontent.com/assets/128755/14070772/d4dd3956-f478-11e5-9ce7-f7544d71c73c.png width= 500 />

Spawn as many mailer servers locally using: `LOG_LEVEL=debug MAILER_PORT=10148 npm start` (change port 10148 to others)

**Comment by vladikoff** [comment]
blocked by the PRs mentioned above.

**Comment by vladikoff** [comment]
blocked by train-66 deploy

**Comment by vladikoff** [comment]
Closed in favour of https://github.com/mozilla/fxa-features/issues/1
