### ISSUE TITLE
Close out FxA-84 "ReCAPTCHA" milestone

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa#154]
#### PR Order:
 
- [ ] feature doc: https://github.com/mozilla/fxa/pull/153
- [ ] customs: https://github.com/mozilla/fxa-customs-server/pull/114
- [ ] auth: https://github.com/mozilla/fxa-auth-server/pull/1276
- [ ] content: https://github.com/mozilla/fxa-content-server/pull/3782

### Testing

To test, make sure fxa-customs-server is connected:
* start https://github.com/mozilla/fxa-customs-server and `memcached`
* start fxa-auth-server with `CUSTOMS_SERVER_URL=http://127.0.0.1:7000` (change in `.env.dev`)
* trigger attempt limit via the content server (submit > 3 login attempts)

**Comment by seanmonstar** [comment]
@vladikoff anything more to do here? Does the feature need to die in Aha! and such also?

Or are we converting this to the "email captcha" idea instead?

**Comment by rfk** [comment]
Yes, I think let's "wontfix" the card in Aha, and spin up a new one for an email-confirmation-based approach

**Comment by seanmonstar** [comment]
@rfk I either cannot figure out Aha (probably), or don't have permission (probaby): https://mozilla.aha.io/features/FXA-84

**Comment by rfk** [comment]
I've marked the card "will not implement" in aha
