### ISSUE TITLE
H2 metrics tracking dashboards

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa#21]
We need to track additional high-level metrics to judge whether we're hitting our goals for the second half of the year, which means we need more graphs on https://metrics.services.mozilla.com/accounts-dashboard/ or a linked dashboard.

Our priority themes are "user control" and "connected experience" and we'll measure their success by:

- [ ] Percentage of accounts that have a mobile device connected
- [ ] Percentage of accounts that have multiple devices connected
- [ ] Number of new multi-device connections made per day
- [ ] Churn, i.e. how many users stop using the service after 1 day, 1 week, 1 month, etc
- [ ] Churn for multi-device users
- [ ] Percentage of accounts that have customized profile data (name, avatar, etc)

We're not collecting a lot of this data currently, so this will probably depend on some backend data-model adjustments.  /cc @philbooth w.r.t short-term priorities for backend work.

**Comment by rfk** [comment]
This has been broken down into smaller FEATURE bugs, closing
