### ISSUE TITLE
[Meta] Async/await conversion of auth server routes and libs

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/fxa#2305]
Copying over the list of routes from #2286. Add your name next to a checkbox item if you start refactoring it.

- [x] account.js **@chenba**, #3655
- [x] attached-clients.js (already using async/await)
- [x] defaults.js **@shane-tomlinson** 
- [x] devices-and-sessions.js **@philbooth**, #2301
- [x] emails.js **@chenba** https://github.com/mozilla/fxa/pull/2324
- [X] idp.js (made no promises)
- [X] index.js (made no promises)
- [x] oauth.js (already using async/await)
- [ ] password.js **@6a68 working on this one**
- [x] recovery-codes.js **@philbooth**, #2387
- [x] recovery-key.js **@philbooth**, #2386
- [x] security-events.js (already using async/await)
- [x] session.js **@philbooth**, #2384
- [x] sign.js @dannycoates
- [x] signin-codes.js **@philbooth**, #2383
- [x] sms.js **@philbooth**, #2382
- [x] subscriptions.js (already using async/await)
- [x] support.js (already using async/await)
- [x] token-codes.js **@philbooth**, #2381
- [x] totp.js
- [x] unblock-codes.js PR #2292
- [x] util.js
- [x] utils/clients.js (made no promises)
- [x] utils/email.js  (made no promises)
- [x] utils/oauth.js (already using async/await)
- [x] utils/request_helper.js  (made no promises)
- [x] utils/signin.js **shane-tomlinson**
- [x] utils/signup.js  (@bbangert)
- [x] utils/subscriptions.js (already using async/await)
- [x] utils/otp.js  (@bbangert)
- [x] validators.js  (made no promises)

Some non-routes libs that we can also investigate and convert:

(Note, the number at the end is the number of instances of `.then` in the file)

- [x] metrics/amplitude.js (3) (@shane-tomlinson)
- [x] metrics/events.js (8) (@shane-tomlinson)
- [x] metrics/context.js (3) (@bbangert)
- [x] crypto/random.js (3)
- [x] crypto/password.js (5)
- [x] scheme-refresh-token.js (5) (@bbangert)
- [x] customs.js (5) (@bbangert)
- [x] subhub/client.js (1)
- [x] features.js (1)
- [x] cache.js (4) (@bbangert)
- [x] server.js (6) (@bbangert)
- [x] db.js (51) (@bbangert)
- [x] pushbox.js (2)
- [x] backendService.js (2)  
- [x] oauthdb/index.js (1)
- [x] oauthdb/utils.js (3)
- [x] log.js (1)
- [x] error.js (5) (no promises, just "au*then*tication")
- [x] senders/index.js (2) (no promises, just "au*then*tication")
- [x] senders/translator.js (2) @lmorchard, #2421
- [ ] senders/sms.js (5) 
- [ ] senders/email.js (15) 
- [x] signer.js (3)  (@bbangert)
- [x] profile/updates.js (2)  (@bbangert)
- [x] push.js (4) (@bbangert)
- [x] devices.js (4) (@bbangert)
- [x] authMethods.js (11) (@bbangert)
- [x] tokens/bundle.js (4) (@bbangert)
- [x] tokens/password_forgot_token.js (1) (@bbangert)
- [x] tokens/key_fetch_token.js (3) (@bbangert)
- [x] tokens/token.js (6) (@bbangert)
- [x] tokens/session_token.js (5) (@bbangert)
- [x] email/bounces.js (6) (@bbangert)
- [x] email/delivery.js (1) (@bbangert)

┆Issue is synchronized with this [Jira Epic](https://jira.mozilla.com/browse/FXA-297)
┆Issue Number: FXA-297

**Comment by clouserw** [comment]
epics are tracked in jira
