### ISSUE TITLE
4.2.4 Standardize package directory structure and npm script names

### ISSUE THREAD

**Issue by meandavejustice** [mozilla/fxa#2579]
package directory structure suggestions / questions:
- [ ] consolidate configs into parent directory when applicable
- [ ] standardize/document what we are going to call directories with sources. We currently have `app/`, `src/`, `server/`, `client/`, and `lib/`.
- [x] In addition to standardizing npm scripts names, `lint` and other command buried by `react-scripts` should be available within the package.
- [x] ~~We are using both `npm-shrinkwrap.json` vs `package-lock.json` we should just use one~~ [use `package-lock.json` everywhere](https://github.com/mozilla/fxa/pull/2234#issuecomment-525629351)
- [ ] use renovate for each package
- [ ] review lerna
- [x] We have nested `.github` directories in packages, we should only have one at the parent level for issue/pull request templates etc..
- [x] remove all instances of `.editorconfig` (no longer necessary now that we have standardjs)
- [x] all docs should be in a top level directory(to the package) called `docs/`
- [x] monorepo docs should link to each package docs
-  [x] individual markdown files CODE_OF_CONDUCT.md etc. should be deduped
- [x] `fxa-shared` is totally different than other packages, that's probably fine, but should be documented.
- [ ] Docker related files should follow same pattern
-  [ ] configuration should be documented in parent directory and consistent. We now have `version.json`, `default.json`, `dev.json`.
- [ ] l10n?

#### possible shared configs?
  - .editorconfig
  - .nvmrc
  - .sass-lint.yml
  - .prettierrc
  - tsconfig.json
  - tslint.json
  - webpack.config.js
  - .circleci/
  - .travis.yml
  - .rustfmt.toml
  - Cargo.lock
  - Cargo.toml
  - Dockerfile
  - Dockerfile-tag
  - rust-toolchain
  - version.json
  - config/
    - default.json
    - dev.json
  - types/
  - .storybook/
  - coverage/
  - public/
  - env
  - test-setup.ts
  - jest.config.js
  - .nsprc

**Comment by shane-tomlinson** [comment]
@meandavejustice - I love this list of suggestions and agree with all of them, I reckon that if all of this were implemented developer happiness would increase as well.

There may be some standalone issues for some of these, e.g., I know we have [discussed replacing npm-shrinkwrap.json with package-lock.json](https://github.com/mozilla/fxa/issues/694#issuecomment-481626221) for some time, and can't find the original issue.

**Comment by philbooth** [comment]
Does this overlap with #694? Can we close that in favour of this, or are they sufficiently different to keep both open?

**Comment by meandavejustice** [comment]
#3082

**Comment by meandavejustice** [comment]
The remaining bullet points of this issue should be moved into a phase 2 epic issue which can be tracked over the next quarter or 2. Some of these are blocked or de-prioritized.

#### consolidate configs in parent directories, where applicable.
a good chunk of consolidating configs was done this quarter, we can go deeper into this once we are using one dockerfile
#### standardize/document what we are going to call directories with sources. We currently have app/, src/, server/, client/, and lib/.
  Some work was done on this, already. This is a lower priority
#### dockerfile consolidation
This is something we want to do eventually, though it will be lower priority depending on the work that comes down the pipeline in Q1
#### app config files
A couple of updates were done with this just by completing some of the other tasks on in this okr. Would be nice to move this into phase 2, again not a big pain point. More of a nice to have. This can also only go so far as we aren't using the same server libraries in each package.
#### l10n
I included this as a thing to explore the state of. We currently use `get-text` in content server, and have no plans to update to fluent atm. However we do have an issue for adding fluent to the payments server. #3610 This falls outside the definition of "standardization issues"

**Comment by meandavejustice** [comment]
Closing as tasks for this quarter have been completed, opened https://github.com/mozilla/fxa/issues/3627 for phase 2
