### ISSUE TITLE
Project Standardization efforts Phase 2

### ISSUE THREAD

**Issue by meandavejustice** [mozilla/fxa#3627]
Still open for more tasks. Opening from https://github.com/mozilla/fxa/issues/2579#issuecomment-564185766

- [ ] consolidate configs in parent directories, where applicable. blocked by #785 
- [ ] standardize/document what we are going to call directories with sources. We currently have app/, src/, server/, client/, and lib/.
- [ ] dockerfile consolidation (#785) 
- [ ] standardize app configuration files

┆Issue is synchronized with this [Jira Epic](https://jira.mozilla.com/browse/FXA-33)
┆Issue Number: FXA-33
