### ISSUE TITLE
FxA Multiple Devices metrics

### ISSUE THREAD

**Issue by billmaggs** [mozilla/fxa#42]
As a FF product group member I want to know how many FxA users are using multiple devices or profiles.

I want to know how many users are using 2 devices or profiles

I want to know how many users are using 3 or more devices

**Comment by rfk** [comment]
/cc @philbooth.  After a product/project discussion last week, we decided it's more important to work on this from a metrics standpoint first rather than from a "session status dashboard" perspective.  The set of enabling work is broadly similar though:

- [ ] Add last access time to login sessions (https://github.com/mozilla/fxa-auth-server/issues/983)
- [ ] Add user agent information to login sessions (https://github.com/mozilla/fxa-auth-server/issues/983)
- [ ] Add optional client-provided device ID to login sessions (https://github.com/mozilla/fxa-auth-server/issues/988)
- [ ] Have Desktop Firefox pass the sync client GUID as its `device` ID when logging into Sync 
- [ ] Have Fennec pass the sync client GUID as its `device` ID when logging into Sync 
- [ ] Have Firefox for iOS pass the sync client GUID as its `device` ID when logging into Sync
- [ ] Add scripting to extract the core multi-device metrics from the db and dump them into our metrics pipeline

**Comment by rfk** [comment]
Exporting these FEATURE cards from Aha has not turned out to be useful in practise, I'm closing them in favour of more direct use of Aha.

This feature lives at: https://mozilla.aha.io/features/FXA-21
