### ISSUE TITLE
Allow trusted internal apps to read profile information without user interaction

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa#53]
I'm revamping this oauth-server bug as a feature card: https://github.com/mozilla/fxa-oauth-server/issues/125

As a developer of a trusted internal application, I want to be able to read the profile information associated with an FxA user id without having to have the user in the loop.  Two concrete examples:

* The payments app, when sending confirmations or receipts, would like to know the most recent email address and locale preference for the user.
* The basket service would like to look up the user's current email address, and the types of devices they have connected to their account.

---------

Work needed to accomplish this:

- [ ] Registering Service Clients https://github.com/mozilla/fxa-oauth-server/issues/327
- [ ] Accept JWTs for authorization tokens https://github.com/mozilla/fxa-oauth-server/issues/328
- [ ] Document Service Clients https://github.com/mozilla/fxa-oauth-server/issues/329

**Comment by rfk** [comment]
The concrete implementation here will likely look a lot like "OAuth2 Service Tokens" and feel very similar to the way it works in Google's infrastructure:

  https://developers.google.com/identity/protocols/OAuth2ServiceAccount

@edmoz @billmaggs we'll need to coordinate with the payments team to determine the right timeline for this, but I think we need to ship it this quarter.

@seanmonstar since you're driving this effort, I've assigned the feature card to you.

**Comment by billmaggs** [comment]
Will check with Andy McKay on timing for payments. Their dates have been
slipping.

**Comment by billmaggs** [comment]
Feedback from Andy is that this is no longer an immediate priority for them, and that Q4 or even Q1 would be fine for their purposes.

**Comment by seanmonstar** [comment]
Does that affect us, or still planning this for Q3?

**Comment by billmaggs** [comment]
I assume the basket team still needs this this quarter; the payments team does not. Ryan, is that the case?

**Comment by rfk** [comment]
Yes, let's still aim to get it done this quarter, it will be useful for a variety of more-internal stuff as well as for payments, kinto etc as external consumers.

**Comment by seanmonstar** [comment]
I've updated this issue to include a list of implementation details needed to fully close this.

**Comment by rfk** [comment]
Exporting these FEATURE cards from Aha has not turned out to be useful in practise, I'm closing them in favour of more direct use of Aha.

This feature lives at: https://mozilla.aha.io/features/FXA-31

**Comment by rfk** [comment]
I also created a milestone and migrated the existing issues into it, so we don't lose any context from this bug:

  https://waffle.io/mozilla/fxa?milestone=FxA-31:%20service%20tokens
