### ISSUE TITLE
Improve CSS workflow & use it to refactor avatar uploads (epic)

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa#623]
parent of https://github.com/mozilla/fxa-content-server/issues/6196
parent of https://github.com/mozilla/fxa-content-server/issues/6165

* [x] Understand the current CSS workflow https://github.com/mozilla/fxa-content-server/issues/6196
* [x] Modernize the CSS building pipeline https://github.com/mozilla/fxa-content-server/issues/6165
  * [x] Switch to latest Webpack tools and latest version of SASS. [**Example**](https://github.com/mozilla/notes/blob/master/src/sidebar/app/app.js#L12).
* [ ] Remove `grunt-contrib-cssmin` (minify css with webpack?), `grunt-sass`,
  * [x] Investigate if we can use CSS for checkboxes: https://github.com/mozilla/fxa-content-server/issues/6029 and drop [fxa-checkbox](https://github.com/mozilla/fxa-content-server/blob/28ad88fb6fa63b07cc328cb288b97af942d99f32/package.json#L52)
  * [x] Investigate if we can remove the [fontello FONT and use SVGS](https://github.com/mozilla/fxa-content-server/issues/6154)
  * [x] What are these  https://github.com/mozilla/fxa-content-server/issues/6262 ? 
* [x] Finally use all the new tooling we have to modernize the avatar uploader https://github.com/mozilla/fxa-content-server/issues/3485
* [x] Investigate https://github.com/mozilla/fxa-content-server/issues/6268
* [x] Upgrade the `webrtc-adapter-test` to latest WebRTC adapter: https://github.com/mozilla/fxa-content-server/blob/28ad88fb6fa63b07cc328cb288b97af942d99f32/package.json#L115, upgrade `blueimp-canvas-to-blob`? and other dependencies used in that module
* [x] Test on iOS https://github.com/mozilla/fxa-content-server/issues/5313
* [x] Use a dynamic import to bundle all avatar related code and fetch it separatly from the main app bundle. [Example](https://github.com/mozilla/fxa-content-server/blob/e0bd497f918659421bacf2f9545002a46c6ffecc/app/scripts/lib/crypto/scoped-keys.js#L13)
* [x] Investigate if we can handle large avatars better https://github.com/mozilla/fxa-content-server/issues/5359
* [x] Investigate if we can process GIFs: https://github.com/mozilla/fxa-content-server/issues/5638

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-754)
┆Issue Number: FXA-754

**Comment by LZoog** [comment]
Closing as all issues are closed, and #559 will be placed in another epic.
