### ISSUE TITLE
Store & manage active subscriptions per user

### ISSUE THREAD

**Issue by lmorchard** [mozilla/fxa#707]
Related to #706 

- [x] #775 Define table schema from SubHub fields (lots of different pieces touching this)
- [x] #775 New auth DB table with columns to match subset of fields shared with SubHub.
- [x] #775 New auth DB stored procedures for CRUD on active subscriptions table.
- [x] #775 In-memory mock implementation for fxa-auth-db-mysql
- [x] #775 Real mysql implementation for fxa-auth-db-mysql
- [x] #775 Implement fxa-auth-db-mysql API changes for CRUD on active subscriptions procedures.
